

# EXAMPLE WORKFLOW USE CASE:
# Start with core services: docker compose --profile transaction --profile customer up --detach
# Later add more: docker compose --profile employees up --detach
# Scale existing: docker compose --profile transaction up --scale transaction-service=3 --detach
# Add final service: docker compose --profile travel-packages up --detach
# Down scale: docker compose --profile transaction down --scale transaction-service=1 --detach


# TO buil
#docker compose --profile customer --profile employees --profile expenses --profile rent-car --profile travel-packages --profile transaction build --no-cache

# Start all services (if you want them all)
# docker compose --profile customer --profile employees --profile expenses --profile rent-car --profile travel-packages --profile transaction up --detach

services:

  # Customer Service
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile.customer
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/customer-service/private
      - travel-volume:/app/dist/apps/customer-service/logs
    networks:
      - travel-network
    restart: unless-stopped


  # Employees Service
  employees-service:
    build:
      context: .
      dockerfile: Dockerfile.employees
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/employees-service/logs
    networks:
      - travel-network
    restart: unless-stopped


  # Expenses Service
  expenses-service:
    build:
      context: .
      dockerfile: Dockerfile.expenses
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/expenses-service/logs
    networks:
      - travel-network
    restart: unless-stopped


  # Rent Car Service
  rent-car-service:
    build:
      context: .
      dockerfile: Dockerfile.rent-car
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/rent-car-service/public
      - travel-volume:/app/dist/apps/rent-car-service/logs
    networks:
      - travel-network
    restart: unless-stopped


  # Travel Packages Service
  travel-packages-service:
    build:
      context: .
      dockerfile: Dockerfile.travel-packages
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/travel-packages-service/public
      - travel-volume:/app/dist/apps/travel-packages-service/logs
    networks:
      - travel-network
    restart: unless-stopped


  # Transaction Service
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile.transaction
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/transaction-service/logs
    networks:
      - travel-network
    restart: unless-stopped

  # Report Service
  report-service:
    build:
      context: .
      dockerfile: Dockerfile.report
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/report-service/logs
    networks:
      - travel-network
    restart: unless-stopped

  
  # Live Chat Service
  live-chat-service:
    build:
      context: .
      dockerfile: Dockerfile.live-chat
    environment:
      - NODE_ENV=production
    volumes:
      - travel-volume:/app/dist/apps/live-chat-service/logs
    networks:
      - travel-network
    restart: unless-stopped


networks:
  cloudflare-network:
    external: true
  travel-network:
    external: true

volumes:
  travel-volume:
    external: true    
