

services:

  # Customer Service
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile.customer
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist/apps/customer-service/private:/private
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

  # Employees Service
  employees-service:
    build:
      context: .
      dockerfile: Dockerfile.employees
    environment:
      - NODE_ENV=production
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

  # Expenses Service
  expenses-service:
    build:
      context: .
      dockerfile: Dockerfile.expenses
    environment:
      - NODE_ENV=production
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

  # Rent Car Service
  rent-car-service:
    build:
      context: .
      dockerfile: Dockerfile.rent-car
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist/apps/rent-car-service/public:/public
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

  # Travel Packages Service
  travel-packages-service:
    build:
      context: .
      dockerfile: Dockerfile.travel-packages
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist/apps/travel-packages-service/public:/public
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

  # Transaction Service
  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile.transaction
    environment:
      - NODE_ENV=production
    networks:
      - travel-network
    restart: unless-stopped
    deploy:
      replicas: 1

networks:
  cloudflare-network:
    external: true
  travel-network:
    external: true

volumes:
  travel-volume:
    external: true    