# Stage 1: Build dependencies
FROM node:22-alpine AS builder

WORKDIR /tmp
COPY . .
RUN npm install -g pnpm
# RUN pnpm install
RUN pnpm build:travel-packages-service:prod

# Stage 2: Final runtime image
FROM node:22-alpine

# Install bash
RUN apk add --no-cache bash

WORKDIR /app
COPY --from=builder tmp/node_modules ./node_modules
COPY --from=builder tmp/dist ./dist
COPY --from=builder tmp/contract ./contract

EXPOSE 3000
CMD ["node", "dist/apps/travel-packages-service/src/main.js"]