

services:
  # Customer Service
  customer-service:
    container_name: customer-service
    build:
      context: .
      dockerfile: Dockerfile.customer
    environment:
      - NODE_ENV=production
    volumes:
      - ./contract:/app/contract
      - ./apps/customer-service/private:/app/customer-service/private
    networks:
      - travel-network
    restart: unless-stopped

  # Employees Service
  employees-service:
    container_name: employees-service
    build:
      context: .
      dockerfile: Dockerfile.employees
    environment:
      - NODE_ENV=production
    volumes:
      - ./contract:/app/contract
    networks:
      - travel-network
    restart: unless-stopped

  # Expenses Service
  expenses-service:
    container_name: expenses-service
    build:
      context: .
      dockerfile: Dockerfile.expenses
    environment:
      - NODE_ENV=production
    volumes:
      - ./contract:/app/contract
    networks:
      - travel-network
    restart: unless-stopped

  # Rent Car Service
  rent-car-service:
    container_name: rent-car-service
    build:
      context: .
      dockerfile: Dockerfile.rent-car
    environment:
      - NODE_ENV=production
    volumes:
      - ./contract:/app/contract
      - ./apps/rent-car-service/public:/app/rent-car-service/public
    networks:
      - travel-network
    restart: unless-stopped

  # Travel Packages Service
  travel-packages-service:
    container_name: travel-packages-service
    build:
      context: .
      dockerfile: Dockerfile.travel-packages
    environment:
      - NODE_ENV=production
    volumes:
      - ./contract:/app/contract
      - ./apps/travel-packages-service/public:/app/travel-packages-service/public
    networks:
      - travel-network
    restart: unless-stopped

  # Transaction Service
  transaction-service:
    container_name: transaction-service
    build:
      context: .
      dockerfile: Dockerfile.transaction
    environment:
      - NODE_ENV=production
      - SERVICE_INSTANCE=2
    volumes:
      - ./contract:/app/contract
    networks:
      - travel-network
    restart: unless-stopped

networks:
  cloudflare-network:
    external: true
  travel-network:
    external: true

volumes:
  travel-volume:
    external: true    