syntax = "proto3";
package auth;
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

// Request message for getting a customer by ID
message GetCustomerRequest {
  int32 id = 1;
}

// Response message containing customer details
message GetCustomerResponse {
  int32 id = 1;
  string name = 2;
  string phone_number = 3;
  string country_origin = 4;
  string email = 5;
}

message RegisterCustomerRequest{
  string email = 1;
  string password = 2;
  string name = 3;
  string phoneNumber = 4;
  string countryOrigin = 5;
}

message RegisterCustomerResponse{
  int32 id = 1;
  string jwtToken = 2;
}


// Service definition for customer operations
service CustomerGrpcService {
  rpc GetCustomer (GetCustomerRequest) returns (GetCustomerResponse);
  rpc RegisterCustomer (RegisterCustomerRequest) returns (RegisterCustomerResponse);
} 