apiVersion: v1
kind: ConfigMap
metadata:
  name: expenses-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  AUTH_GRPC_PORT: "21001"
  REDIS_PORT: "6379"
  EMP_AUTH_CLIENT: "employees-service.default.svc.cluster.local:21001"
  REDIS_HOST: "redis.default.svc.cluster.local"
  SYNCHRONIZE: "0"
  JWT_EXPIRES: "1d"
  DATABASE_SSL: "true"