apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  TRANSACTION_GRPC_PORT: "21001"
  REDIS_PORT: "6379"
  CUS_AUTH_CLIENT: "customer-service.default.svc.cluster.local:21001"
  EMP_AUTH_CLIENT: "employees-service.default.svc.cluster.local:21001"
  TRAVEL_PACKAGE_CLIENT: "travel-packages-service.default.svc.cluster.local:21001"
  CAR_CLIENT: "rent-car-service.default.svc.cluster.local:21001"
  REDIS_HOST: "redis.default.svc.cluster.local"
  SYNCHRONIZE: "0"
  JWT_EXPIRES: "1d"
  DATABASE_SSL: "true"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  EXCHANGE_RATE_API: "https://open.er-api.com/v6/latest/USD"
  PAYPAL_BASE_URL: "https://api-m.sandbox.paypal.com"
  CLIENT_URL: 
