apiVersion: v1
kind: Secret
metadata:
  name: transaction-secret
type: Opaque
stringData:
  DATABASE_URL: 
  SLAVE_DATABASE_URL: 
  JWT_KEY: 
  MAIL_USER: 
  MAIL_PASSWORD: 
  MAIL_FROM: 
  MIDTRANS_CLIENT_KEY: 
  MIDTRANS_SERVER_KEY: 
  PAYPAL_CLIENT_ID: 
  PAYPAL_CLIENT_SECRET: 
