apiVersion: v1
kind: ConfigMap
metadata:
  name: employees-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  AUTH_GRPC_PORT: "21001"
  REDIS_PORT: "6379"
  REDIS_HOST: "redis.default.svc.cluster.local"
  EMP_AUTH_CLIENT: "employees-service.default.svc.cluster.local:21001"
  BOOKINGS_CLIENT: "transaction-service.default.svc.cluster.local:21001"
  SYNCHRONIZE: "0"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  FRONTEND_URL: 
  JWT_EXPIRES: "1d"
  DATABASE_SSL: "true"
