apiVersion: v1
kind: ConfigMap
metadata:
  name: live-chat-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  CUS_AUTH_CLIENT: "customer-service.default.svc.cluster.local:21001"
  EMP_AUTH_CLIENT: "employees-service.default.svc.cluster.local:21001"
  SYNCHRONIZE: "0"
  JWT_EXPIRES: "1d"
  DATABASE_SSL: "true"
